<?php echo $this->headTitle('Main')->setSeparator(' - ')->setAutoEscape(false) ?>
<div class="container main">
    <div class="page-header">
        <h1 id="timeline">History</h1>
    </div>
    <ul class="timeline">
        <li>
            <div class="timeline-badge"><i class="glyphicon glyphicon-check"></i></div>
            <div class="timeline-panel">
                <div class="timeline-heading">
                    <h4 class="timeline-title">Mussum ipsum cacilds</h4>
                    <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> 25/01/2014</small></p>
                </div>
                <div class="timeline-body">
                    <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , 
                        depois divoltis porris, paradis. Paisis, filhis, espiritis santis. 
                        Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. 
                </div>
            </div>
        </li>
        <li class="timeline-inverted">
            <div class="timeline-badge warning"><i class="glyphicon glyphicon-credit-card"></i></div>
            <div class="timeline-panel">
                <div class="timeline-heading">
                    <h4 class="timeline-title">Mussum ipsum cacilds</h4>
                      <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> 25/01/2014</small></p>
                </div>
                <div class="timeline-body">
                    <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis.
                        Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis.
                        Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo.
                    <p>Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. 
                </div>
            </div>
        </li>
    </ul>
</div>