<?php echo $this->headTitle('Login')->setSeparator(' - ')->setAutoEscape(false) ?>
<div class="container" id="login">
    <div class="row vertical-offset-100">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please sign in</h3>
                </div>
                <div class="panel-body">
                    <?= $this->viewForm($this->loginForm,'cUser',['action'=>'login']); ?>
                </div>
            </div>
        </div>
    </div>
</div>